#!/usr/bin/env python3
"""
find_master.py — given a skill (or a sect), list the masters who teach it,
where they stand, and (optionally) the walk route there from --from.

Usage:
  python find_master.py --skill sword                       # all masters teaching 剑法
  python find_master.py --skill lan-hua-fu-xue-shou         # a specific named skill
  python find_master.py --sect shaolin                      # all shaolin masters
  python find_master.py --skill sword --from 扬州           # + walk route to each master

Data: data/masters.json (generated by build_kb.py: is_master NPCs joined to their room).
Route reuses route.py's multi-source BFS over data/map.json.

Notes:
  * masters.json npc_id is the master's LPC path. Some masters are class *mixins*
    (/kungfu/class/...) with no fixed room -> room_id null; those are shown but
    can't be routed to (the concrete NPC that inherits them carries the room).
  * combat_exp is the master's own exp; many teaching applies gate the *student's*
    exp/family — consult quests.md / the class file for the real learn prereqs.
"""
import argparse, json, os, sys

HERE = os.path.dirname(os.path.abspath(__file__))
KB = os.path.dirname(HERE)

def load_masters():
    p = os.path.join(KB, 'data', 'masters.json')
    return json.load(open(p, encoding='utf-8')).get('masters', [])

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--skill', help='skill_id to learn (e.g. sword, force, lan-hua-fu-xue-shou)')
    ap.add_argument('--sect', help='filter by sect code (e.g. shaolin, emei, wudang)')
    ap.add_argument('--from', dest='src', help='optional start (room_id / area / 中文区名) to route from')
    ap.add_argument('--masters', default=os.path.join(KB, 'data', 'masters.json'))
    args = ap.parse_args()
    if not args.skill and not args.sect:
        ap.error('give at least one of --skill / --sect')

    masters = load_masters()
    hits = []
    for m in masters:
        if args.sect and m.get('sect') != args.sect:
            continue
        if args.skill:
            teaches = m.get('teaches') or []
            if isinstance(teaches, dict):
                teaches = list(teaches.keys())
            if args.skill not in teaches:
                continue
        hits.append(m)

    if not hits:
        what = args.skill or f'门派 {args.sect}'
        print(f'没有找到教 {what} 的师傅（masters.json 共 {len(masters)} 位）。'
              f'\n可能该武功由具体 NPC 而非 is_master 标记的师傅传授，或抓取遗漏——可在 npcs.json 里 grep teaches。')
        return

    hits.sort(key=lambda m: (m.get('combat_exp') or 0))
    title = args.skill or args.sect
    print(f'教「{title}」的师傅 {len(hits)} 位（按自身 combat_exp 升序，越低通常越好接近/学习）:\n')

    rmap = cn2code = None
    if args.src:
        sys.path.insert(0, HERE)
        import route as R
        rmap = R.load_map(os.path.join(KB, 'data', 'map.json'))
        cn2code = R.load_areas(os.path.join(KB, 'data', 'map.json'))
        _, starts = R.resolve_set(args.src, rmap, cn2code)

    for m in hits:
        loc = m.get('room_short') or '(无固定房间/类mixin)'
        rid = m.get('room_id') or '-'
        teach = m.get('teaches') or []
        if isinstance(teach, dict):
            teach = list(teach.keys())
        print(f"  {m['name']} ({m['npc_id']})  sect={m.get('sect')}  exp={m.get('combat_exp')}")
        print(f"     在: {loc} [{rid}]   教: {', '.join(teach)}")
        if args.src and m.get('room_id'):
            _, goals = R.resolve_set(m['room_id'], rmap, cn2code)
            path, goal = R.bfs(starts, goals, rmap)
            if path is None:
                print(f"     路线: 静态图无连通路径（多半跨区特殊出口，见 warnings.json）")
            elif not path:
                print(f"     路线: 已在该房间")
            else:
                steps = ' '.join(f'{d}' for d, _ in path)
                print(f"     路线({len(path)}步): {steps}")
        print()

if __name__ == '__main__':
    main()
